"""init

Revision ID: a739809cfd65
Revises: 
Create Date: 2026-05-19 13:37:58.929898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a739809cfd65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('year', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_student_id'), ['student_id'], unique=True)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('attendance_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_student_id'), ['student_id'], unique=False)

    op.create_table('face_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_dataset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_dataset_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_dataset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_dataset_student_id'))

    op.drop_table('face_dataset')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_attendance_date'))

    op.drop_table('attendance')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_student_id'))

    op.drop_table('students')
    op.drop_table('admins')
    # ### end Alembic commands ###
